### ISSUE TITLE
Navbar-collapse state bug

### ISSUE THREAD

**Issue by mkarnicki** [creativetimofficial/material-kit-pro#20]
I believe this is different from #13 .

Repro steps:
1. use material-kit, add navbar, open on phone or in narrow browser
2. click menu (menu opens)
3. click menu (menu hides)

4. click menu again (menu opens)
5. click outside of menu (menu hides, but differently)
6. if you now click menu, you see it slide in and "animate out" immediately
7. if you click menu icon, header will adjust itself, but you're in step 6-7 loop
The collapse state is inversed. Man this is buggy...

Workaround:
8. click menu (shows, but hides immediately)
9. dismiss the invisible menu by clicking on the left side of page (not menu)

Menu will work again.

Please fix this. I bought material-kit a month ago, started integrating it today, and spent hours on #13 and now I get hit by this. Thanks.

**Comment by dragosct10** [comment]
Hi @mkarnicki! Please can you give us a link of you're project to see more exactly what is the problem? I followed the steps that you mentioned but nothing happens. 

Regards,
Dragos

**Comment by mkarnicki** [comment]
Hi @dragosct10 , sure. I'm temporarily working on this domain: http://drutujemy.pl but will shortly move over here http://zadrutowani.pl (just in case the first link doesn't work no more).

The steps above describe the problem well. Point 5. is, to be exact:
"5. To hide the menu, don't touch hamburger icon, but touch outside of menu or navbar area, on the area of the page -- which is to the left of the opened (uncollapsed) menu"

Thanks for looking into this. I hope I didn't screw up CSS. I often copy paste from Creative Tim's templates and examples, but maybe I broke something on the way?

**Comment by mkarnicki** [comment]
Hi, I moved the website. Updated previous post to reflect the new domain. Issue still persists. If you close the menu by touching to the left of the uncollapsed menu pane, you break it.

**Comment by dragosct10** [comment]
Hi @mkarnicki! Sorry for the late response. I opened you're project and it looks very good, congrats! For the problem with the navbar collapse please go in your html page and delete the `id="collapsible-navbar"` from the div with class `.navbar-collapse.collapse`. I will attach an image to see more clearly. You need to delete this `id` because this activate the javascript from Bootstrap and like you see in the image that I attached, navbar-collapse div automatically receive the property with value `height: 0` and in this way your collapse disappear. Please let us know if everything is working fine!

Regards,
Dragos


<img width="891" alt="screen shot 2017-06-06 at 13 01 50" src="https://cloud.githubusercontent.com/assets/17456857/26824122/c4a93c5a-4ab8-11e7-9f7d-615b2083373e.png">

**Comment by mkarnicki** [comment]
@dragosct10 Thank you so much, that was it! I really tried to debug this (and saw what you noticed), but I couldn't figure what was affecting the height value. It was Bootstrap JS, d'uh! :)

Thank you!
