### ISSUE TITLE
DateTimePicker v4.17.37 not workign in Modal

### ISSUE THREAD

**Issue by alexsuarex** [creativetimofficial/material-kit-pro#31]
I put a DateTimePicker in a Modal and this does not work, could help me with this, I have already searched and I have not found anything

![captura de pantalla 2017-07-23 a las 1 39 39 p m](https://user-images.githubusercontent.com/30379797/28495729-6e10842a-6fac-11e7-8c39-eef69ce7bca7.png)

**Comment by MostafaAttia** [comment]
@alexsuarex  I think you have to initialize it in your script like
`$(function () {
        $('#dobpicker').datetimepicker({
            viewMode: 'years'
        });
    });`

and see the documentation here: [https://github.com/Eonasdan/bootstrap-datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker)

**Comment by alexsuarex** [comment]
yes of course, I initialized, actually when I put datetimepicker outside modal it working well, I dont know why in modal dont working

**Comment by alexandru-paduraru** [comment]
@alexsuarex thank you for using our product and sorry for the late response. When the modal is hidden the javascript is not finding it, because it has the "display:none" property. That means the browser cannot see that element. So I recommend you to init the Datetimepicker code after the modal was opened. More about the modal events here: http://getbootstrap.com/javascript/#modals-events

You will have something like this:

```
$('#myModal').on('shown.bs.modal', function (e) {
  $('#datepicker').datetimepicker({ viewMode: 'years' });
})
```
Hope this helps.

Best,
Alex
