### ISSUE TITLE
Dynamic Shadow in Material Kit Pro V 1.1.1 doesn't work in Internet Explorer

### ISSUE THREAD

**Issue by weblackey** [creativetimofficial/material-kit-pro#38]
Same as the background content of rotating cards, this problem can be reproduced simply by opening your Material Kit live preview in Internet Explorer. This is with Internet Explorer set to all defaults.

Dynamic shadows are nice to have but not critical. The missing content on the back of rotating cards is very critical if an ecommerce "buy" button is placed on the back of a rotating card as in your ecommerce example.

Since both of these features don't work in IE but do work in other browsers, maybe there is some common initialization or debounce ?

**Comment by alexandru-paduraru** [comment]
@weblackey thank you for the information and for using our product. As we checked and tried multiple times to fix the rotating cards, we found out that basically, IE doesn't support that at all. It is not something that we are not trying to fix, it is a problem with the IE transform/translate/rotate etc. properties. 

We are looking at this moment to see if a complete change of the structure of the card will work. If not we will see if this is a feature that will be removed completely from our product or if we will add a message which will check the browser and inform the user that the website is using some features that are not supported by IE and we recommend them to upgrade to a better browser. The problem is that there are less than 1% of people who are using IE...so hard to make a decision.

What do you think?

Best,
Alex

**Comment by weblackey** [comment]
Hi Alex, the card does rotate in Internet Explorer. The only issue is that it doesn't show the content of the back. Maybe all that's needed is to check if Internet Explorer is being used and then refresh or repaint the content ? It could be a small bug. If you can't find it, instead of pulling the feature, could you put this feature in your free version of Material Kit and consider asking people on github or stackoverflow to see if they can spot it ? Even if the card doesn't rotate in IE and simply paints the back content when you hover or do the manual "rotate" that's perfectly ok. But completely missing the content on the back would not work for your ecommerce example where the buy button is on the back.

Regarding your usage statistics, it would not be accurate to say that Internet Explorer is less than 1%. Current data shows 3% overall, but that's only because mobile is so popular. Among desktop PC users the market share of IE is very high, since it is the default browser of Windows 7. Not everybody has upgraded to Windows 10, and not everybody trusts to give all their info to google so Internet Explorer still has at least 30% market share among desktop PC users. Maybe you don't care about desktop PC users but the whole point of using your kit that is based on Bootstrap and responsive design is that you have a beautiful solution for targeting BOTH mobile AND non-mobile i.e. desktop computers, of which Windows PCs are the overwhelming majority.

**Comment by alexandru-paduraru** [comment]
@weblackey Thank you for the solution, showing the back on hover as a backup case just for IE sounds better than just removing it. We are doing some more tests today and come back with something that is working in 1-2 days. 

You're right with the IE usage, I see that v11 and Edge are still getting some popularity, last time when I've checked the stats were different. We will have a solution for this, no worries :D

**Comment by dragosct10** [comment]
Hi @weblackey! We just came with an update for Material Kit PRO. Please take the latest update `1.2.0` and the rotating cards will work on IE. Dynamic Shadow are now disabled for IE and will work only on the other browsers.
