### ISSUE TITLE
Select & Meteor

### ISSUE THREAD

**Issue by msnraul** [creativetimofficial/material-kit-pro#9]
I am having trouble trying to make the select work in Meteor. I'm using Blaze for templates.
There are no other css/jss than yours in the project.

This is what I get when using the code in the example at foms/extendended.html:
Any advice would be apreciated.

<img width="342" alt="2" src="https://cloud.githubusercontent.com/assets/14353274/24450220/628cd28a-147a-11e7-9a56-49e6b58b31a9.png">
<img width="352" alt="1" src="https://cloud.githubusercontent.com/assets/14353274/24450221/6290f734-147a-11e7-91c2-b8fe3a67de98.png">

As you can see there are some styles lacking and the transition isn't the same neither.

Thanks in advance for any help.

**Comment by alexandru-paduraru** [comment]
@msnraul thank you for using our product. Are you sure it is Material Kit PRO (the current repo)? Because there is no forms/extended.html in this product. It is only in Material Dashboard PRO -> http://demos.creative-tim.com/material-dashboard-pro/examples/forms/extended.html 

Assuming you are using the Dashboard, Please make sure the selectpicker function is called like in the material-dashboard.js line 87

```js
//    Activate bootstrap-select
    if($(".selectpicker").length != 0){
        $(".selectpicker").selectpicker();
    }
```

If you use Material Kit PRO, make sure the select is activated using the dropdown function like how it is activated on material-kit.js line 37 

```js 
$(".select").dropdown({ "dropdownClass": "dropdown-menu", "optionClass": "" });
```

Let us know your status.

Best,
Alex
